import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import pkg from "../../package.json";
import Header from "./Header.tsx";
import Footer from "./Footer.tsx";
console.log(pkg);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header msg={"Next.js: " + pkg.dependencies.next}>
          aaa
        </Header>
        {children}
        <Footer msg="bar">
          bbb
        </Footer>
      </body>
    </html>
  );
}
